### ISSUE TITLE
PyTorch Geometric Temporal

### ISSUE THREAD

**Issue by benedekrozemberczki** [Covid-19-papers/Does-Air-Quality-Really-Impact-COVID-19-Clinical-Severity#1]
Hi There,

Did you cite the PyTorch Geometric Temporal paper?

Benedek

**Comment by Covid-19-papers** [comment]
Thank you for your note, Benedek.
We have added a citation/link on the Readme file.
Also, sent you an e-mail with further comments.

Best,
